// <auto-generated />
using System;
using FewaTelemedicine.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FewaTelemedicine.Migrations
{
    [DbContext(typeof(FewaDbContext))]
    partial class FewaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FewaTelemedicine.Domain.Models.DoctorsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Clinic")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("MedicalDegree")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("NameTitle")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mst_Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "doctor",
                            UserName = "doctor"
                        });
                });

            modelBuilder.Entity("FewaTelemedicine.Domain.Models.ParametersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ParameterGroupName")
                        .HasColumnType("text");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("text");

                    b.Property<string>("ValueDataType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mst_Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParameterGroupName = "Hospital",
                            ParameterName = "Name",
                            ParameterValue = "Fewa Telemedicine",
                            ValueDataType = "string"
                        },
                        new
                        {
                            Id = 2,
                            ParameterGroupName = "Hospital",
                            ParameterName = "Description",
                            ParameterValue = "..Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate dolorem facilis aliquam veritatis, quam debitis beatae quaerat id totam dolor, ipsa dolorum, at iusto. Explicabo numquam, nostrum iste voluptatem maiores.",
                            ValueDataType = "string"
                        },
                        new
                        {
                            Id = 3,
                            ParameterGroupName = "Hospital",
                            ParameterName = "ContactNumber",
                            ParameterValue = "98465175",
                            ValueDataType = "string"
                        },
                        new
                        {
                            Id = 4,
                            ParameterGroupName = "Hospital",
                            ParameterName = "Email",
                            ParameterValue = "dummy@email.com",
                            ValueDataType = "string"
                        },
                        new
                        {
                            Id = 5,
                            ParameterGroupName = "Hospital",
                            ParameterName = "LogoPath",
                            ParameterValue = "img/logo.png",
                            ValueDataType = "string"
                        });
                });

            modelBuilder.Entity("FewaTelemedicine.Domain.Models.PatientsAttendedModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MeetingId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("txn_Patients_Attended");
                });
#pragma warning restore 612, 618
        }
    }
}
